Repository Dani-gr/M9, pull requests merged in 2023-05, with the labels that each got.

#4 Now it works, I swear!
  .gitignore
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CambDivisaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ChatEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClienteEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntityPK.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/DireccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/EmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ExtraccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/MensajeEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/OperacionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntityPK.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/TransferenciaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/UsuarioEntity.java
  BancoDB.sql
Labels: bug

#6 Carlos
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/DireccionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CambDivisaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ChatEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClienteEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntityPK.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentasSospechosasEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/DireccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/EmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ExtraccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/MensajeEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/OperacionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntityPK.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/TransferenciaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/UsuarioEntity.java
  BancApp/src/main/webapp/WEB-INF/view/gestorView.jsp
  BancoDB-v2.sql
  BancoDBv2.mwb
  BancoDBv2.mwb.bak
Labels: enhancement

#7 Login conecta por fin bien con el menú
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ClienteController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/ClienteEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/EmpresaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolusuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/UsuarioRepository.java
  BancApp/src/main/webapp/WEB-INF/view/cabecera.jsp
  BancApp/src/main/webapp/WEB-INF/view/cambiodivisa.jsp
  BancApp/src/main/webapp/WEB-INF/view/cliente.jsp
  BancApp/src/main/webapp/WEB-INF/view/enespera.jsp
  BancApp/src/main/webapp/WEB-INF/view/login.jsp
  BancApp/src/main/webapp/WEB-INF/view/menu.jsp
  BancApp/src/main/webapp/WEB-INF/view/registro.jsp
  BancApp/src/main/webapp/WEB-INF/view/roleView.jsp
  BancApp/src/main/webapp/WEB-INF/view/transferencia.jsp
  BancApp/src/main/webapp/WEB-INF/view/vistaRoles.jsp
Labels: bug

#11 Base de datos mini cambio
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ClienteController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/CambDivisaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/ClienteEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/CuentaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/EmpresaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/ExtraccionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/OperacionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/TransferenciaRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CambDivisaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ChatEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClienteEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentasSospechosasEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/DireccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/EmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ExtraccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/MensajeEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/OperacionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/TransferenciaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/UsuarioEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroOperaciones.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/OrdenarOperaciones.java
  BancApp/src/main/webapp/WEB-INF/view/cambiodivisa.jsp
  BancApp/src/main/webapp/WEB-INF/view/cliente.jsp
  BancApp/src/main/webapp/WEB-INF/view/extraccion.jsp
  BancApp/src/main/webapp/WEB-INF/view/registro.jsp
  BancApp/src/main/webapp/WEB-INF/view/transferencia.jsp
  BancoDB-v4.sql
  BancoDBv2.mwb
  BancoDBv2.mwb.bak
Labels: enhancement

#15 Control de errores en las operaciones, y solución de issues #16 y #17
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ClienteController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CambDivisaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ChatEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClienteEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ClientesEmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CuentasSospechosasEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/DireccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/EmpresaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/ExtraccionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/MensajeEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/OperacionEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/TransferenciaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/UsuarioEntity.java
  BancApp/src/main/webapp/WEB-INF/view/cabeceraMenu.jsp
  BancApp/src/main/webapp/WEB-INF/view/cambiodivisa.jsp
  BancApp/src/main/webapp/WEB-INF/view/extraccion.jsp
  BancApp/src/main/webapp/WEB-INF/view/menu.jsp
  BancApp/src/main/webapp/WEB-INF/view/registro.jsp
  BancApp/src/main/webapp/WEB-INF/view/transferencia.jsp
  BancoDB-v6.sql
  BancoDBv3.mwb
  BancoDBv3.mwb.bak
  BancoDBv4.mwb
Labels: bug, enhancement

#19 ¿Cajero terminado?
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolusuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CambDivisaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ChatEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ClienteEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ClientesEmpresaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ClientesempresaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CuentaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CuentasSospechosasEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/DireccionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/EmpresaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ExtraccionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/MensajeEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/OperacionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/RolEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/RolusuarioEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/TransferenciaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/UsuarioEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/RolusuarioEntity.java
  BancApp/src/main/webapp/WEB-INF/view/cambiodivisa.jsp
  BancApp/src/main/webapp/WEB-INF/view/menu.jsp
Labels: bug, enhancement

#18 Maria
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ClienteController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/EmpresaController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/UsuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroAsociadosEmpresa.java
  BancApp/src/main/webapp/WEB-INF/view/cabecera.jsp
  BancApp/src/main/webapp/WEB-INF/view/cabeceraMenu.jsp
  BancApp/src/main/webapp/WEB-INF/view/datosEmpresa.jsp
  BancApp/src/main/webapp/WEB-INF/view/datosUsuario.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestionSociosYAut.jsp
  BancApp/src/main/webapp/WEB-INF/view/menu.jsp
  BancApp/src/main/webapp/WEB-INF/view/operaciones.jsp
  BancApp/src/main/webapp/WEB-INF/view/registro.jsp
  BancApp/src/main/webapp/WEB-INF/view/registroNuevoSocio.jsp
Labels: bug, enhancement

#26 Ver operaciones listo + añadido que se vea el saldo en Datos de mi em…
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/EmpresaController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/OperacionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/UsuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroAsociadosEmpresa.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroOperacionesEmpresa.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/OrdenarOperacionesEmpresa.java
  BancApp/src/main/webapp/WEB-INF/view/datosEmpresa.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestionSociosYAut.jsp
  BancApp/src/main/webapp/WEB-INF/view/operaciones.jsp
Labels: enhancement

#27 Gestor 100% funcional
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/CuentaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolusuarioEntityRepository.java
  BancApp/src/main/webapp/WEB-INF/view/OperacionesClienteGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/cabeceraGestor.jsp
  BancApp/src/main/webapp/WEB-INF/view/cabeceraMenuGestor.jsp
  BancApp/src/main/webapp/WEB-INF/view/cuentasInactivasGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorEmpresaView.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorParticularView.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/seguridadGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitanteGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesActivacionGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesAltaGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesDesbloqueoEmpresaGestorView.jsp
Labels: bug, enhancement

#28 Controllers de Operaciones y Login migrados
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/RolusuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CambDivisaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ChatEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ClienteEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ClientesEmpresaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CuentaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/CuentasSospechosasEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/DireccionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/EmpresaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/ExtraccionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/MensajeEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/OperacionEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/RolEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/RolusuarioEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/TransferenciaEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dto/UsuarioEntityDTO.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/entity/CambDivisaEntity.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/CambDivisaService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/ClienteService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/CuentaService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/DireccionService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/EmpresaService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/ExtraccionService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/OperacionService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/RolService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/RolusuarioService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/TransferenciaService.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/service/UsuarioService.java
Labels: DTO

#30 Refactor de legibilidad
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ChatController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/ClienteController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/EmpresaController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/GestorController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/LoginController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/controller/OperacionController.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/CambDivisaEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/ExtraccionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/OperacionEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/dao/UsuarioEntityRepository.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroAsociadosEmpresa.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroClientes.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroOperaciones.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/FiltroOperacionesEmpresa.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/OrdenarOperaciones.java
  BancApp/src/main/java/es/proyectotaw/banca/bancapp/ui/OrdenarOperacionesEmpresa.java
  BancApp/src/main/webapp/WEB-INF/view/OperacionesClienteGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/cabeceraGestor.jsp
  BancApp/src/main/webapp/WEB-INF/view/cabeceraMenuGestor.jsp
  BancApp/src/main/webapp/WEB-INF/view/cambiodivisa.jsp
  BancApp/src/main/webapp/WEB-INF/view/chatDetails.jsp
  BancApp/src/main/webapp/WEB-INF/view/chats.jsp
  BancApp/src/main/webapp/WEB-INF/view/cuentasInactivasGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/datosUsuario.jsp
  BancApp/src/main/webapp/WEB-INF/view/enespera.jsp
  BancApp/src/main/webapp/WEB-INF/view/extraccion.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestionSociosYAut.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorEmpresaView.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorParticularView.jsp
  BancApp/src/main/webapp/WEB-INF/view/gestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/menu.jsp
  BancApp/src/main/webapp/WEB-INF/view/operaciones.jsp
  BancApp/src/main/webapp/WEB-INF/view/registro.jsp
  BancApp/src/main/webapp/WEB-INF/view/seguridadGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitanteGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesActivacionGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesAltaGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/solicitudesDesbloqueoEmpresaGestorView.jsp
  BancApp/src/main/webapp/WEB-INF/view/transferencia.jsp
Labels: refactor
